services:
  - type: web
    name: starcy-backend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: APNS_BUNDLE_ID
        value: com.star.starcyyy
      - key: APNS_KEY_ID
        sync: false
      - key: APNS_TEAM_ID
        sync: false
      - key: APNS_KEY_BASE64
        sync: false